{"level":"info","message":"Parse LiveQuery Server starts running","timestamp":"2018-12-28T17:56:45.627Z"}
{"level":"info","message":"Parse LiveQuery Server starts running","timestamp":"2018-12-28T18:00:49.661Z"}
{"level":"info","message":"Parse LiveQuery Server starts running","timestamp":"2018-12-28T18:07:59.493Z"}
{"level":"info","message":"Parse LiveQuery Server starts running","timestamp":"2018-12-28T18:12:33.117Z"}
{"level":"info","message":"Parse LiveQuery Server starts running","timestamp":"2018-12-28T18:14:57.869Z"}
{"level":"info","message":"Parse LiveQuery Server starts running","timestamp":"2018-12-28T18:17:47.834Z"}
{"level":"info","message":"Parse LiveQuery Server starts running","timestamp":"2018-12-28T18:24:28.786Z"}
{"level":"info","message":"Parse LiveQuery Server starts running","timestamp":"2018-12-28T18:28:37.016Z"}
{"error":{"message":"Clients aren't allowed to perform the find operation on the installation collection.","code":119},"level":"error","message":"Error handling request: { Error: Clients aren't allowed to perform the find operation on the installation collection.\n    at enforceRoleSecurity (/home/tu/ExpressTest/getting-MEAN/node_modules/parse-server/lib/rest.js:182:13)\n    at Object.find (/home/tu/ExpressTest/getting-MEAN/node_modules/parse-server/lib/rest.js:31:3)\n    at ClassesRouter.handleFind (/home/tu/ExpressTest/getting-MEAN/node_modules/parse-server/lib/Routers/ClassesRouter.js:42:26)\n    at route.req (/home/tu/ExpressTest/getting-MEAN/node_modules/parse-server/lib/Routers/ClassesRouter.js:168:19)\n    at /home/tu/ExpressTest/getting-MEAN/node_modules/parse-server/lib/PromiseRouter.js:175:7\n    at Layer.handle [as handle_request] (/home/tu/ExpressTest/getting-MEAN/node_modules/parse-server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/tu/ExpressTest/getting-MEAN/node_modules/parse-server/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/home/tu/ExpressTest/getting-MEAN/node_modules/parse-server/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/home/tu/ExpressTest/getting-MEAN/node_modules/parse-server/node_modules/express/lib/router/layer.js:95:5)\n    at /home/tu/ExpressTest/getting-MEAN/node_modules/parse-server/node_modules/express/lib/router/index.js:281:22\n  message:\n   \"Clients aren't allowed to perform the find operation on the installation collection.\",\n  code: 119 }","timestamp":"2018-12-28T18:28:43.821Z"}
{"message":"Clients aren't allowed to perform the find operation on the installation collection.","stack":"Error: Clients aren't allowed to perform the find operation on the installation collection.\n    at enforceRoleSecurity (/home/tu/ExpressTest/getting-MEAN/node_modules/parse-server/lib/rest.js:182:13)\n    at Object.find (/home/tu/ExpressTest/getting-MEAN/node_modules/parse-server/lib/rest.js:31:3)\n    at ClassesRouter.handleFind (/home/tu/ExpressTest/getting-MEAN/node_modules/parse-server/lib/Routers/ClassesRouter.js:42:26)\n    at route.req (/home/tu/ExpressTest/getting-MEAN/node_modules/parse-server/lib/Routers/ClassesRouter.js:168:19)\n    at /home/tu/ExpressTest/getting-MEAN/node_modules/parse-server/lib/PromiseRouter.js:175:7\n    at Layer.handle [as handle_request] (/home/tu/ExpressTest/getting-MEAN/node_modules/parse-server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/tu/ExpressTest/getting-MEAN/node_modules/parse-server/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/home/tu/ExpressTest/getting-MEAN/node_modules/parse-server/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/home/tu/ExpressTest/getting-MEAN/node_modules/parse-server/node_modules/express/lib/router/layer.js:95:5)\n    at /home/tu/ExpressTest/getting-MEAN/node_modules/parse-server/node_modules/express/lib/router/index.js:281:22","code":119,"level":"error","timestamp":"2018-12-28T18:28:43.823Z"}
{"level":"info","message":"Parse LiveQuery Server starts running","timestamp":"2018-12-28T18:29:09.359Z"}
{"level":"info","message":"Parse LiveQuery Server starts running","timestamp":"2018-12-28T18:30:21.575Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)","timestamp":"2018-12-28T18:37:09.498Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)","timestamp":"2018-12-28T18:37:09.758Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)","timestamp":"2018-12-28T18:37:09.760Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)","timestamp":"2018-12-28T18:37:09.923Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)","timestamp":"2018-12-28T18:37:10.096Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)","timestamp":"2018-12-28T18:37:10.481Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)","timestamp":"2018-12-28T18:37:10.668Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)","timestamp":"2018-12-28T18:37:11.240Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)","timestamp":"2018-12-28T18:37:11.336Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)","timestamp":"2018-12-28T18:37:11.416Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)","timestamp":"2018-12-28T18:37:11.512Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)","timestamp":"2018-12-28T18:37:11.712Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)","timestamp":"2018-12-28T18:37:11.820Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)","timestamp":"2018-12-28T18:37:12.380Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)","timestamp":"2018-12-28T18:37:12.758Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)","timestamp":"2018-12-28T18:37:12.828Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)","timestamp":"2018-12-28T18:37:13.611Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)","timestamp":"2018-12-28T18:37:15.640Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)","timestamp":"2018-12-28T18:37:15.642Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)","timestamp":"2018-12-28T18:37:15.780Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)","timestamp":"2018-12-28T18:37:15.904Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)","timestamp":"2018-12-28T18:37:16.057Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)","timestamp":"2018-12-28T18:37:16.204Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)","timestamp":"2018-12-28T18:37:16.790Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)","timestamp":"2018-12-28T18:37:16.885Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)","timestamp":"2018-12-28T18:37:17.287Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)","timestamp":"2018-12-28T18:37:18.571Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)","timestamp":"2018-12-28T18:37:20.424Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)","timestamp":"2018-12-28T18:37:20.484Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)","timestamp":"2018-12-28T18:37:20.885Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)","timestamp":"2018-12-28T18:37:21.544Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:188:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:276:13)\n    at Connection.emit (events.js:188:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/home/tu/ExpressTest/getting-MEAN/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:276:13)\n    at Socket.emit (events.js:188:13)","timestamp":"2018-12-28T18:37:23.386Z"}
{"level":"info","message":"Parse LiveQuery Server starts running","timestamp":"2018-12-28T18:41:47.948Z"}
{"message":"Object not found.","stack":"Error: Object not found.\n    at then.then.result (/home/tu/ExpressTest/getting-MEAN/node_modules/parse-server/lib/Controllers/DatabaseController.js:518:17)\n    at process.internalTickCallback (internal/process/next_tick.js:77:7)","code":101,"level":"error","timestamp":"2018-12-28T18:52:15.203Z"}
{"message":"Object not found.","stack":"Error: Object not found.\n    at then.then.result (/home/tu/ExpressTest/getting-MEAN/node_modules/parse-server/lib/Controllers/DatabaseController.js:518:17)\n    at process.internalTickCallback (internal/process/next_tick.js:77:7)","code":101,"level":"error","timestamp":"2018-12-28T18:52:23.287Z"}
{"message":"Object not found.","stack":"Error: Object not found.\n    at then.then.result (/home/tu/ExpressTest/getting-MEAN/node_modules/parse-server/lib/Controllers/DatabaseController.js:518:17)\n    at process.internalTickCallback (internal/process/next_tick.js:77:7)","code":101,"level":"error","timestamp":"2018-12-28T18:52:52.603Z"}
{"message":"Object not found.","stack":"Error: Object not found.\n    at then.then.result (/home/tu/ExpressTest/getting-MEAN/node_modules/parse-server/lib/Controllers/DatabaseController.js:518:17)\n    at process.internalTickCallback (internal/process/next_tick.js:77:7)","code":101,"level":"error","timestamp":"2018-12-28T18:52:58.669Z"}
{"level":"info","message":"Parse LiveQuery Server starts running","timestamp":"2018-12-28T18:55:01.105Z"}
{"level":"info","message":"Parse LiveQuery Server starts running","timestamp":"2018-12-28T18:55:27.319Z"}
{"message":"Object not found.","stack":"Error: Object not found.\n    at then.then.result (/home/tu/ExpressTest/getting-MEAN/node_modules/parse-server/lib/Controllers/DatabaseController.js:518:17)\n    at process.internalTickCallback (internal/process/next_tick.js:77:7)","code":101,"level":"error","timestamp":"2018-12-28T18:56:55.803Z"}
{"message":"Object not found.","stack":"Error: Object not found.\n    at then.then.result (/home/tu/ExpressTest/getting-MEAN/node_modules/parse-server/lib/Controllers/DatabaseController.js:518:17)\n    at process.internalTickCallback (internal/process/next_tick.js:77:7)","code":101,"level":"error","timestamp":"2018-12-28T18:56:57.043Z"}
{"message":"Object not found.","stack":"Error: Object not found.\n    at then.then.result (/home/tu/ExpressTest/getting-MEAN/node_modules/parse-server/lib/Controllers/DatabaseController.js:518:17)\n    at process.internalTickCallback (internal/process/next_tick.js:77:7)","code":101,"level":"error","timestamp":"2018-12-28T18:56:58.016Z"}
{"message":"Object not found.","stack":"Error: Object not found.\n    at then.then.result (/home/tu/ExpressTest/getting-MEAN/node_modules/parse-server/lib/Controllers/DatabaseController.js:518:17)\n    at process.internalTickCallback (internal/process/next_tick.js:77:7)","code":101,"level":"error","timestamp":"2018-12-28T19:02:53.143Z"}
{"message":"Object not found.","stack":"Error: Object not found.\n    at then.then.result (/home/tu/ExpressTest/getting-MEAN/node_modules/parse-server/lib/Controllers/DatabaseController.js:518:17)\n    at process.internalTickCallback (internal/process/next_tick.js:77:7)","code":101,"level":"error","timestamp":"2018-12-28T19:15:58.515Z"}
{"message":"Object not found.","stack":"Error: Object not found.\n    at then.then.result (/home/tu/ExpressTest/getting-MEAN/node_modules/parse-server/lib/Controllers/DatabaseController.js:518:17)\n    at process.internalTickCallback (internal/process/next_tick.js:77:7)","code":101,"level":"error","timestamp":"2018-12-28T19:16:06.699Z"}
{"message":"Object not found.","stack":"Error: Object not found.\n    at then.then.result (/home/tu/ExpressTest/getting-MEAN/node_modules/parse-server/lib/Controllers/DatabaseController.js:518:17)\n    at process.internalTickCallback (internal/process/next_tick.js:77:7)","code":101,"level":"error","timestamp":"2018-12-28T19:16:14.075Z"}
{"level":"error","message":"Uncaught internal server error. Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17) Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)","timestamp":"2018-12-28T19:16:20.813Z"}
{"level":"error","message":"Uncaught internal server error. Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17) Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)","timestamp":"2018-12-28T19:16:21.015Z"}
{"level":"error","message":"Uncaught internal server error. Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17) Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)","timestamp":"2018-12-28T19:16:21.368Z"}
{"level":"error","message":"Uncaught internal server error. Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17) Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)","timestamp":"2018-12-28T19:16:22.235Z"}
{"level":"error","message":"Uncaught internal server error. Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17) Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)","timestamp":"2018-12-28T19:16:22.298Z"}
{"level":"error","message":"Uncaught internal server error. Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17) Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)","timestamp":"2018-12-28T19:16:22.358Z"}
{"level":"error","message":"Uncaught internal server error. Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17) Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)","timestamp":"2018-12-28T19:16:22.585Z"}
{"level":"error","message":"Uncaught internal server error. Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17) Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)","timestamp":"2018-12-28T19:16:23.037Z"}
{"level":"error","message":"Uncaught internal server error. Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17) Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)","timestamp":"2018-12-28T19:16:23.559Z"}
{"level":"error","message":"Uncaught internal server error. Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17) Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)","timestamp":"2018-12-28T19:16:23.689Z"}
{"level":"error","message":"Uncaught internal server error. Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17) Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)","timestamp":"2018-12-28T19:16:33.228Z"}
{"level":"error","message":"Uncaught internal server error. Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17) Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)","timestamp":"2018-12-28T19:16:33.378Z"}
{"level":"error","message":"Uncaught internal server error. Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17) Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)","timestamp":"2018-12-28T19:16:33.608Z"}
{"level":"error","message":"Uncaught internal server error. Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17) Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)","timestamp":"2018-12-28T19:16:33.865Z"}
{"level":"error","message":"Uncaught internal server error. Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17) Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)","timestamp":"2018-12-28T19:16:34.114Z"}
{"level":"error","message":"Uncaught internal server error. Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17) Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)","timestamp":"2018-12-28T19:16:34.172Z"}
{"level":"error","message":"Uncaught internal server error. Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17) Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)","timestamp":"2018-12-28T19:16:34.343Z"}
{"level":"error","message":"Uncaught internal server error. Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17) Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)","timestamp":"2018-12-28T19:16:34.402Z"}
{"level":"error","message":"Uncaught internal server error. Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17) Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)","timestamp":"2018-12-28T19:16:34.484Z"}
{"level":"error","message":"Uncaught internal server error. Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17) Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":50,\"3\":33,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":184}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)","timestamp":"2018-12-28T19:16:35.857Z"}
{"message":"Object not found.","stack":"Error: Object not found.\n    at then.then.result (/home/tu/ExpressTest/getting-MEAN/node_modules/parse-server/lib/Controllers/DatabaseController.js:518:17)\n    at process.internalTickCallback (internal/process/next_tick.js:77:7)","code":101,"level":"error","timestamp":"2018-12-28T19:17:05.107Z"}
{"message":"Object not found.","stack":"Error: Object not found.\n    at then.then.result (/home/tu/ExpressTest/getting-MEAN/node_modules/parse-server/lib/Controllers/DatabaseController.js:518:17)\n    at process.internalTickCallback (internal/process/next_tick.js:77:7)","code":101,"level":"error","timestamp":"2018-12-28T19:17:09.107Z"}
{"level":"error","message":"Uncaught internal server error. Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":53,\"3\":160,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":186}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17) Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":53,\"3\":160,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":186}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)","timestamp":"2018-12-28T19:17:13.746Z"}
{"level":"error","message":"Uncaught internal server error. Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":53,\"3\":160,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":186}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17) Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":53,\"3\":160,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":186}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)","timestamp":"2018-12-28T19:17:13.819Z"}
{"level":"error","message":"Uncaught internal server error. Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":53,\"3\":160,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":186}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17) Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":53,\"3\":160,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":186}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)","timestamp":"2018-12-28T19:17:13.889Z"}
{"level":"error","message":"Uncaught internal server error. Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":53,\"3\":160,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":186}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17) Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":53,\"3\":160,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":186}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)","timestamp":"2018-12-28T19:17:14.423Z"}
{"level":"error","message":"Uncaught internal server error. Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":53,\"3\":160,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":186}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17) Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":53,\"3\":160,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":186}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)","timestamp":"2018-12-28T19:17:14.643Z"}
{"level":"error","message":"Uncaught internal server error. Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":53,\"3\":160,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":186}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17) Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":53,\"3\":160,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":186}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)","timestamp":"2018-12-28T19:17:14.704Z"}
{"level":"error","message":"Uncaught internal server error. Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":53,\"3\":160,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":186}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17) Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":53,\"3\":160,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":186}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)","timestamp":"2018-12-28T19:17:15.028Z"}
{"level":"error","message":"Uncaught internal server error. Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":53,\"3\":160,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":186}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17) Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":53,\"3\":160,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":186}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)","timestamp":"2018-12-28T19:17:15.140Z"}
{"level":"error","message":"Uncaught internal server error. Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":53,\"3\":160,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":186}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17) Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":53,\"3\":160,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":186}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)","timestamp":"2018-12-28T19:17:15.879Z"}
{"level":"error","message":"Uncaught internal server error. Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":53,\"3\":160,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":186}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17) Error: object [{\"_bsontype\":\"ObjectID\",\"id\":{\"0\":92,\"1\":37,\"2\":53,\"3\":160,\"4\":209,\"5\":168,\"6\":118,\"7\":48,\"8\":74,\"9\":0,\"10\":94,\"11\":186}}] is not a valid ObjectId\n    at serializeObjectId (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:288:11)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:932:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/home/tu/ExpressTest/getting-MEAN/node_modules/bson/lib/bson/parser/serializer.js:938:17)","timestamp":"2018-12-28T19:17:16.855Z"}
{"level":"info","message":"Parse LiveQuery Server starts running","timestamp":"2018-12-28T19:33:41.904Z"}
{"level":"info","message":"Parse LiveQuery Server starts running","timestamp":"2018-12-28T20:07:21.021Z"}
{"level":"info","message":"Parse LiveQuery Server starts running","timestamp":"2018-12-28T20:08:20.495Z"}
{"level":"info","message":"Parse LiveQuery Server starts running","timestamp":"2018-12-28T20:08:55.538Z"}
{"level":"info","message":"Parse LiveQuery Server starts running","timestamp":"2018-12-28T20:09:42.656Z"}
{"level":"info","message":"Parse LiveQuery Server starts running","timestamp":"2018-12-28T20:10:44.492Z"}
{"level":"info","message":"Parse LiveQuery Server starts running","timestamp":"2018-12-28T20:13:46.347Z"}
{"level":"info","message":"Parse LiveQuery Server starts running","timestamp":"2018-12-28T20:15:09.797Z"}
{"level":"info","message":"Parse LiveQuery Server starts running","timestamp":"2018-12-28T20:17:39.237Z"}
{"level":"info","message":"Parse LiveQuery Server starts running","timestamp":"2018-12-28T21:37:44.679Z"}
{"level":"info","message":"Parse LiveQuery Server starts running","timestamp":"2018-12-28T21:50:56.344Z"}
{"level":"info","message":"Parse LiveQuery Server starts running","timestamp":"2018-12-28T21:51:56.844Z"}
{"level":"info","message":"Parse LiveQuery Server starts running","timestamp":"2018-12-28T21:52:15.036Z"}
{"level":"info","message":"Parse LiveQuery Server starts running","timestamp":"2018-12-28T21:56:12.532Z"}
